[package]
name = "brain"
version.workspace = true
edition.workspace = true

[dependencies]
shared.workspace = true
anyhow.workspace = true
log.workspace = true
tokio = { version = "1", features = ["full"] }
uuid = "1.17.0"
btleplug = "0.11.8"
futures = "0.3.31"
pretty_env_logger = "0.5.0"
rand = { version = "0.9", features = ["small_rng"], default-features = false }
